name: CI Workflow

on:
  push:
    branches:
      - dev

jobs:
  prettier:
    name: Compiler
    needs: []
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm install
      - run: npm run prettier:check
